// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuadroApp.Data;

#nullable disable

namespace QuadroApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228232856_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsGroep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfwerkingsGroepen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsOptie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AfvalPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("AfwerkingsGroepId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KostprijsPerM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeverancierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VasteKost")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<char>("Volgnummer")
                        .HasColumnType("TEXT");

                    b.Property<int>("WerkMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinstMarge")
                        .HasPrecision(6, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierId");

                    b.HasIndex("AfwerkingsGroepId", "Volgnummer")
                        .IsUnique();

                    b.ToTable("AfwerkingsOpties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportRowLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId");

                    b.ToTable("ImportRowLogs");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inserted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportSessions");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Instelling", b =>
                {
                    b.Property<string>("Sleutel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Waarde")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Sleutel");

                    b.ToTable("Instellingen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BtwNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gemeente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opmerking")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Straat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Leverancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Naam")
                        .IsUnique();

                    b.ToTable("Leveranciers");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Offerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BtwBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeadlineDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeplandeDatum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeschatteMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoorschotBetaald")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KortingPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerPrijsIncl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opmerking")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubtotaalExBtw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotaalInclBtw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VoorschotBedrag")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Offertes");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.OfferteRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalStuks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AfgesprokenPrijsExcl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BreedteCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BtwBedrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiepteKernId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExtraPrijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraWerkMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GlasId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoogteCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InlegBreedteCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InlegHoogteCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Korting")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegacyCode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OpklevenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opmerking")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassePartout1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassePartout2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RugId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubtotaalExBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotaalExcl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotaalInclBtw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TypeLijstId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiepteKernId");

                    b.HasIndex("GlasId");

                    b.HasIndex("OfferteId");

                    b.HasIndex("OpklevenId");

                    b.HasIndex("PassePartout1Id");

                    b.HasIndex("PassePartout2Id");

                    b.HasIndex("RugId");

                    b.HasIndex("TypeLijstId");

                    b.ToTable("OfferteRegels");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.TypeLijst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AfvalPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BreedteCm")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InventarisKost")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDealer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LaatsteUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Levcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeverancierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumVoorraad")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opmerking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrijsPerMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Serie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VasteKost")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VoorraadMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("WerkMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinstMargeFactor")
                        .HasPrecision(6, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeverancierId");

                    b.ToTable("TypeLijsten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AfhaalDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BijgewerktOp")
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferteId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StockReservationProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotaalPrijsIncl")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfferteId")
                        .IsUnique();

                    b.ToTable("WerkBonnen");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkTaak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BenodigdeMeter")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BestelDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuurMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeplandTot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeplandVan")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBesteld")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpVoorraad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OfferteRegelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("WeekNotitie")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("WerkBonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeplandVan");

                    b.HasIndex("OfferteRegelId");

                    b.HasIndex("WerkBonId");

                    b.ToTable("WerkTaken");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsOptie", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.AfwerkingsGroep", "AfwerkingsGroep")
                        .WithMany("Opties")
                        .HasForeignKey("AfwerkingsGroepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.Leverancier", "Leverancier")
                        .WithMany()
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AfwerkingsGroep");

                    b.Navigation("Leverancier");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportRowLog", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.ImportSession", "ImportSession")
                        .WithMany("RowLogs")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSession");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Offerte", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Klant", "Klant")
                        .WithMany("Offertes")
                        .HasForeignKey("KlantId");

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.OfferteRegel", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "DiepteKern")
                        .WithMany()
                        .HasForeignKey("DiepteKernId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Glas")
                        .WithMany()
                        .HasForeignKey("GlasId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.Offerte", "Offerte")
                        .WithMany("Regels")
                        .HasForeignKey("OfferteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Opkleven")
                        .WithMany()
                        .HasForeignKey("OpklevenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "PassePartout1")
                        .WithMany()
                        .HasForeignKey("PassePartout1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "PassePartout2")
                        .WithMany()
                        .HasForeignKey("PassePartout2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.AfwerkingsOptie", "Rug")
                        .WithMany()
                        .HasForeignKey("RugId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuadroApp.Model.DB.TypeLijst", "TypeLijst")
                        .WithMany()
                        .HasForeignKey("TypeLijstId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DiepteKern");

                    b.Navigation("Glas");

                    b.Navigation("Offerte");

                    b.Navigation("Opkleven");

                    b.Navigation("PassePartout1");

                    b.Navigation("PassePartout2");

                    b.Navigation("Rug");

                    b.Navigation("TypeLijst");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.TypeLijst", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Leverancier", "Leverancier")
                        .WithMany("TypeLijsten")
                        .HasForeignKey("LeverancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leverancier");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBon", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.Offerte", "Offerte")
                        .WithOne("WerkBon")
                        .HasForeignKey("QuadroApp.Model.DB.WerkBon", "OfferteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offerte");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkTaak", b =>
                {
                    b.HasOne("QuadroApp.Model.DB.OfferteRegel", "OfferteRegel")
                        .WithMany()
                        .HasForeignKey("OfferteRegelId");

                    b.HasOne("QuadroApp.Model.DB.WerkBon", "WerkBon")
                        .WithMany("Taken")
                        .HasForeignKey("WerkBonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferteRegel");

                    b.Navigation("WerkBon");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.AfwerkingsGroep", b =>
                {
                    b.Navigation("Opties");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.ImportSession", b =>
                {
                    b.Navigation("RowLogs");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Klant", b =>
                {
                    b.Navigation("Offertes");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Leverancier", b =>
                {
                    b.Navigation("TypeLijsten");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.Offerte", b =>
                {
                    b.Navigation("Regels");

                    b.Navigation("WerkBon");
                });

            modelBuilder.Entity("QuadroApp.Model.DB.WerkBon", b =>
                {
                    b.Navigation("Taken");
                });
#pragma warning restore 612, 618
        }
    }
}
